### ISSUE TITLE
Issue on Windows

### ISSUE THREAD

**Issue by macumber** [lefticus/decent_ci_runner#3]
I get this when running the setup script on Windows:

./verifyenv.rb:232:in `install_choco`: undefined method `create` for Tempfile:Class (NoMethodError)
        from ./verifyenv.rb:346:in `<main>`

$ ruby -v
ruby 2.0.0p648 (2015-12-16) [x64-mingw32]

**Comment by macumber** [comment]
[google search](https://www.google.com/search?q=.%2Fverifyenv.rb%3A232%3Ain+install_choco%3A+undefined+method+create+for+Tempfile%3AClass&oq=.%2Fverifyenv.rb%3A232%3Ain+install_choco%3A+undefined+method+create+for+Tempfile%3AClass&aqs=chrome..69i57.672j0j7&sourceid=chrome&ie=UTF-8&safe=active#safe=active&q=undefined+method+create+for+Tempfile:Class) indicates Tempfile::create is only in ruby 2.1 and higher?

**Comment by macumber** [comment]
Issue was my old system install of Ruby, I removed that and issue went away
